# Generated by Django 3.2.6 on 2021-09-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('peso', models.FloatField()),
                ('edad', models.DateField()),
                ('sexo', models.IntegerField(choices=[(1, 'Macho'), (2, 'Hembra')])),
                ('descripcion', models.TextField(max_length=60, verbose_name='Descripcion de la mascota')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilcliente')),
            ],
        ),
    ]
