# Generated by Django 3.2.6 on 2021-09-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'Canino'), (2, 'Felino'), (3, 'Roedor'), (4, 'Lagomorfo'), (5, 'Ave'), (6, 'Anfibio'), (7, 'Reptil')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Convencional'), (2, 'No Convencional')], default=3),
            preserve_default=False,
        ),
    ]
