# Generated by Django 3.2.6 on 2021-08-29 20:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=75, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin codigo de area ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
