# Generated by Django 3.2.6 on 2021-09-27 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210926_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladmin',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin codigo de area ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin codigo de area ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='perfilveterinario',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin codigo de area ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono'),
        ),
    ]
